## Unit 10 Assignment - W200 Introduction to Data Science Programming, UC Berkeley MIDS

Write code in this Jupyter Notebook to solve the following problems. Please upload this **Notebook** with your solutions to your GitHub repository in your SUBMISSIONS/week_11 folder by 11:59PM PST the night before class. Do not push the data files to your repo.

This homework assignment is Week 11 which corresponds to the Unit #10 and a small part of Unit #11 async. 

## Objectives
- Demonstrate use of map and filter commands
- Practice list comprehensions and lambda functions
- Understand different ways to manipulate and perform calculations on Numpy arrays including:
-   Changing datatypes, getting the max values in each column and row, calculating the mean of a matrix
-   Matrix value comparisons and slicing of values
- Load a file into a pandas dataframe and demonstrate some filtering

## General Guidelines:

- All calculations need to be done in the functions (that includes any formatting of the output)
- Name your functions exactly as written in the problem statement
- Please have your functions return the answer rather than printing it inside the function
- Do not make a separate input() statement.  The functions will be passed the input as shown in the examples
- The examples given are samples of how we will test/grade your code. Please ensure your functions output the same information
- Answer format is graded - please match the examples
- Docstrings and comments in your code are strongly suggested but won't be graded
- This homework is mostly auto-graded.  The blank code blocks are the auto-grading scripts - please do not delete these!
- Your code needs to be written in the #Your Code Here blocks or it wont be graded correctly.


## Project 2 Proposal

**Reminder!** Please complete your project 2 proposal, as discussed in class and outlined in the project_2 folder. As a group, submit your 1-2 page proposal as a PDF in your group project 2 repo. Please only submit one final version to be graded to your group repo!

This is worth 10 points of your **project 2** grade (not the grade for this homework).

## 1. List, Mapping, Filtering, and Reducing Comprehensions (30 points)

A. Write a function named `compute` below that: 
- Returns the square of any number for integer or floating type values
- Returns the reverse of the content if it is a string
- Or returns the **value None** (not the string 'None') if it is another kind of value.

In [3]:
def compute(value):
    ''' method input int, float or string; returns square of number or reverse of string '''
    
    if type(value) == int:
        # print('This number is an int')
        value = value ** 2
    elif type(value) == float:
        # print('This number is a float')
        value = value ** 2
    elif isinstance(value, str):
        # print('a string')
        value = value[::-1]        
    else:
        # None
        # print('None')
        value = None
    
    return value


In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

B. Now apply the `compute` function made in 1A. (above) using `map` to a list of values. Write this `map` statement in the new function named `map_compute`. Return the values as a `list` (not a `map_object`). You should be able to do this in ONE single line! 

Example function call: 

```map_compute(['cup', '321', 12, ['x'], 4, True])```

Expected returned output: 

```['puc', '123', 144, None, 16, None]```


In [4]:
def map_compute(my_list):
    ''' method calls compute funtion via a map call '''
    
    return list(map(compute, my_list))

map_compute(['cup', '321', 12, ['x'], 4, True])    


['puc', '123', 144, None, 16, None]

In [ ]:
### Autograded cells. Do not remove.

C. Write a new function named `filter_compute` to remove any **integer** values that are less than 5 in your `map` result and return this result as a `list`. You should be able to this in ONE single line. Some pseudo-code below:

- Step 1: Use `map` to apply ```compute``` function from Part 1A to your list (as you did above in 1B)
- Step 2: Use `filter` to apply the above constraint to your output of Step 1. You might want to re-factor your filter logic in a separate function (it won't be counted against the single line constraint imposed above)

Example function call: 
```filter_compute(['cup', '321', 2, ['x'], 4, True])```

Expected returned output: 

```['puc', '123', None, 16, None]```

In [8]:
def filter_compute(my_list):
    ''' method removes any **integer** values that are less than 5 in ''' 
        
    ''' 
        if else in lamda function to return True or False
        lambda <arguments> : <Return Value if condition is True> if <condition> else <Return Value if condition is False>
    ''' 
    
    ''' filter() function accepts a callback() function and a list of elements. It iterates over all elements in list and 
        calls the given callback() function on each element. If callback() returns True then it appends that element in 
        the new list. In the end it returns a new list of filtered elements only.
    '''
    
    return list( # iterate the list and execute the lamda function on each list item
                filter (
                            lambda value : 
                            # if value is an int or float and is less than 5 return False
                            False if ( 
                                      (type(value) == int or 
                                       type(value) == float) and 
                                       value < 5
                                    )
                            else True, # else return True
                            # call map on list of elements
                            map( compute, my_list) 
                        )
                )    

filter_compute(['cup', '321', 2, ['x'], 4, True])
    

['puc', '123', None, 16, None]

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

D. Now that you are an expert in maps and filters, write the above logic from Part 1B & 1C in ONE line using 2 `lambda` functions, 1 for the `map`, and 1 for the `filter` part in the function named `lambda_compute`. This should be one line with one lambda for the map and one lambda for the filter.  Do **NOT** use the lambdas to call the functions you already made in the parts above (1A, 1B or 1C), instead make the same logic in a lambda function. 

Hint: It could be easier to start with separate lambda functions and then combine then into one.

In [9]:
def lambda_compute(my_list):
    ''' method that calls all the previous actions on one line '''     
    
    return list ( 
                 filter ( lambda value :
                            False  if (
                                        (type(value) == int or 
                                         type(value) == float ) and 
                                         value < 5 )
                            else True, 
                            list ( map ( lambda value : value ** 2 
                                        if( type(value) == int or
                                            type(value) == float ) 
                                        else value [::-1] 
                                    if ( type(value) == str) 
                                    else None, my_list )
                                 )
                        )
                )

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

## 2. NumPy (40 points)
In this next section, we will work with NumPy. For each question below, use NumPy functionality to execute the logic of your answer. (**Do not use ```For``` loops!**)

#### Generating Random Data and Filtering That Data

Please run the two cells below to set your random seed. (This makes the 'randomness' of the array the same for everyone)

In [16]:
import numpy as np
np.random.seed(25)
ar = np.random.randn(1000)

In [17]:

# Do NOT change this code!
ar = ar * 100
ar = ar.astype('int8')
ar


array([  22,  102,  -83,  -59,  -95,  -22,  -61,  -73,   51,   86,  -92,
        -23,  -41,  123,    7, -124,  120, -104,  105,  -41,  -27,   -3,
         26,   68,   99,   59,   53,  -29,  -51,  -58,   22,   73,  -96,
         38,   39,   40,   21,  -63,   24,   63,   11,   68,   24,  -70,
         36,  -50,  -22,  -56,   10,  -55,  109,  -90,  -62,  -94,  117,
        -37,  -54,   28,  -20,  118,   72,  -22,   94,   31, -116,   31,
         47,   57,   50,  -62,  -34,   50,   76,  112,   16,  -96,   49,
        -55,   -8,  -60,   -6,  -85,   42,  -27,  119,   -9,   83,  -78,
        104,  -64,   67,   -9,  121,   49, -114,  -53,  -91,  -21,   19,
        -32,   84,   76,   44,   43,  102,  -58,    4,   56, -114,    0,
        -29,   23,   67,  122,  -60,  -16,  -65,  -19,   17,    3, -126,
        -53,   52,   38,  -76,   -5,  -24,   20,  -30,   15,    3,  -32,
        -77,  -33,   54, -115,  -74,  101,   96,  -18,  -54, -109,   43,
        -73,   16,  -67,  -16,  -54,  -35,  -88,   

In [ ]:
## Autograded cells. Do not remove

A. Write code in the function ```reshape``` that takes an array of size 1000 and reshapes the array into a set of five columns with 200 rows. Return this new array and replace the original ```ar``` array with it.

In [18]:
def reshape(my_array):
    ''' method takes an array of size 1000 and reshapes the array into a set of five columns with 
        200 rows.''' 
    
    new_array = np.reshape(my_array, (200, 5))
        
    return new_array

ar = reshape(ar)

print(ar)

[[  22  102  -83  -59  -95]
 [ -22  -61  -73   51   86]
 [ -92  -23  -41  123    7]
 [-124  120 -104  105  -41]
 [ -27   -3   26   68   99]
 [  59   53  -29  -51  -58]
 [  22   73  -96   38   39]
 [  40   21  -63   24   63]
 [  11   68   24  -70   36]
 [ -50  -22  -56   10  -55]
 [ 109  -90  -62  -94  117]
 [ -37  -54   28  -20  118]
 [  72  -22   94   31 -116]
 [  31   47   57   50  -62]
 [ -34   50   76  112   16]
 [ -96   49  -55   -8  -60]
 [  -6  -85   42  -27  119]
 [  -9   83  -78  104  -64]
 [  67   -9  121   49 -114]
 [ -53  -91  -21   19  -32]
 [  84   76   44   43  102]
 [ -58    4   56 -114    0]
 [ -29   23   67  122  -60]
 [ -16  -65  -19   17    3]
 [-126  -53   52   38  -76]
 [  -5  -24   20  -30   15]
 [   3  -32  -77  -33   54]
 [-115  -74  101   96  -18]
 [ -54 -109   43  -73   16]
 [ -67  -16  -54  -35  -88]
 [   9  112  -45   87 -114]
 [ -85   93  -17   41  -28]
 [ -90   48   -4   64    1]
 [ -97   59 -126 -100  -48]
 [  39   62   53   37  -52]
 [  30  -66  -19   9

In [ ]:
### Autograded cells. Do not remove.

B. Now that `ar` is a matrix, create a function named ```row_min_max``` to get the maximum and minimum values from the matrix, row wise. This function returns a tuple of a list of row max values and a list of row min values (in that order). Be sure to remember how many total values you should be outputting (one for every row).

For example: if my_matrix is:

```
4 1 5
5 6 7
4 5 6
```


The returned value should be:

```
([5,7,6], [1,5,4])
```

In [ ]:
def row_min_max(my_matrix):
    ''' method gets the maximum and minimum values from the matrix, row wise.''' 
        
    max_list = []
    min_list = []
    
    for row in my_matrix:
        
        max_list.append( max (row) )
        min_list.append( min (row) )
    
    max_min = (max_list, min_list)
    
    return max_min
    
row_min_max(ar)

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

C. Write a function named ```less_than_mean``` that returns the total **number** of values in the `ar` matrix that are less than the mean of all values in the matrix. This should be a single number.

In [8]:
def calculate_mean(my_matrix, total):
    ''' calculate the mean of the matrix '''
    mean = 0
    
    for row in my_matrix:
        sum_total = sum(row)
        
    mean = sum_total / total
       
    return mean

def less_than_mean(my_matrix):
    # YOUR CODE HERE
    # raise NotImplementedError()
    
    mean = calculate_mean(my_matrix, my_matrix.size)
    less_than_mean = 0
    
    for row in my_matrix:
        for num in row:
            if num < mean:
                less_than_mean += 1
    
    return less_than_mean

print(less_than_mean(ar))

502


In [ ]:
### Autograded cells. Do not remove.

D. Write a function called ```max_position``` that returns the position (as a tuple) of the max value in the passed matrix. 

For example: if ```my_matrix``` is:
```
4 1 5
5 6 7
4 5 6
```
The returned value should be:
```
(1, 2)
```

In [26]:

def max_position(my_matrix):
    ''' returns postion of largest value in the matrix ''' 
    max_value = 0
    
    # loop the rows to find the largest value
    for row in my_matrix:
        if max_value < max(row):
            max_value = max(row)
    
    # loop the rows
    for row in range(200):
        # loop the col
        for col in range(5):
            if my_matrix[row][col] == max_value:
                return (row, col)
    
print(max_position(ar))


(199, 4)


In [ ]:
### Autograded cells. Do not remove.

E. Lastly, write a function named ```select_sum``` that returns the sum of all the values of a boolean array indexed `ar` matrix. Use the boolean array index of the `ar` matrix by: 
- values greater than 100 -boolean or-
- values less than 5 -boolean and- greater than or equal to -20

In [25]:
def select_sum(my_matrix):
    ''' returns the sum of all the values greater than 100 or less than 5 or equal to 20 ''' 

    sum = 0
    
    # loop the matrix
    for i in my_matrix:
        # if greater than 100 
        if [my_matrix > 100]:
            sum += i
        
    return sum   

select_sum(ar)

array([-110,  -76,  -63,   60,  -90], dtype=int8)

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

## 3. Data loading and indexing using Pandas (30 points)

A. For this part of the homework, we will work with the airline safety dataset. As the first step, load the dataset from `airline-safety.csv` by defining the `load_data` function below. Have this function return the following (in order):

1. The entire data frame
2. Total number of rows
3. Total number of columns

In [2]:

import pandas as pd 

def load_data():
    ''' method to load data from file ''' 
    # YOUR CODE HERE
    # load data frame
    
    df = pd.read_csv('airline-safety.csv')
    # load rows    
    num_rows = df.shape[0]
    # load cols
    num_cols = df.shape[1]
    
    return(df, num_rows, num_cols)

df, num_rows, num_cols = load_data()

df.head()



airline  avail_seat_km_per_week  incidents_85_99  \
0             Aer Lingus               320906734                2   
1              Aeroflot*              1197672318               76   
2  Aerolineas Argentinas               385803648                6   
3            Aeromexico*               596871813                3   
4             Air Canada              1865253802                2   

   fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
0                      0                 0                0   
1                     14               128                6   
2                      0                 0                1   
3                      1                64                5   
4                      0                 0                2   

   fatal_accidents_00_14  fatalities_00_14  
0                      0                 0  
1                      1                88  
2                      0                 0  
3                      0                 0  
4                      0                 0

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

B. Write the function `select_airlines` that returns the ith to jth airline name as a **list** (both inclusive) from the dataframe. 

For example: if i=2 and j=5, your code should return 4 airline names: airline name from the 3rd, 4th, 5th and 6th row (assuming that the first row starts from 0). 

##### Note on loc and iloc

Selection Using Label:

To select a column of a DataFrame by column label, the safest and fastest way is to use the .loc method. General usage looks like frame.loc[rowname,colname]. (Reminder that the colon : means "everything"). For example, if we want the color column of a data frame, we would use : ex.loc[:, 'color']

You can also slice across columns. For example, frame.loc[:, 'Name':] would give select the columns Name and the columns after.


In [3]:
def select_airlines(df, i, j):
    ''' method returns the ith to jth airline name as a list ''' 
    
    # frame.loc[row, col]
    airline_names = list(df.loc[i:j,'airline'])
    
    return(airline_names)    

sliced_df = select_airlines(df, 2, 5)

sliced_df


['Aerolineas Argentinas', 'Aeromexico*', 'Air Canada', 'Air France']

In [ ]:
### Autograded cells. Do not remove.

In [ ]:
### Autograded cells. Do not remove.

C. Filtering or slicing with boolean arrays

In your quest for cleaner data, you will undoubtedly filter your data at some point: whether it be for clearing up cases with missing values, culling out fishy outliers, or analyzing subgroups of your data set. Note: compound expressions have to be grouped with parentheses. 

A filter example:  
`df[df[column name] < 5]]`

Write the function `fatalities_filter` to return just the airline names with more than 100 and less than 300 fatalities, between the years 85 and 99. Your function needs to return a **list** of **airline names only**.

In [4]:
def fatalities_filter(df):
    ''' method return just the airline names with more than 100 and less than 300 fatalities, 
        between the years 85 and 99. '''
    
    airlines_names = list(
        # return just the airline names with more than 100 and less than 300 fatalities, 
        # between the years 85 and 99.
        df [ df ['fatalities_85_99'].between(100, 300)] ['airline'] )
    
    return(airlines_names)

fatalities_filter(df)

['Aeroflot*',
 'American*',
 'Egyptair',
 'Ethiopian Airlines',
 'Garuda Indonesia',
 'Iberia',
 'Pakistan International',
 'South African',
 'SWISS*',
 'US Airways / America West*',
 'Vietnam Airlines']

In [ ]:
### Autograded cells. Do not remove.

## If you have feedback for this homework, please submit it using the link below:

http://goo.gl/forms/74yCiQTf6k